version: "3.3"
services:
  webappjs:
    platform: linux/amd64
    image: webapp
    build:
      context: happyhacking-react
      dockerfile: Dockerfile
    ports:
      - "8080:5173"
  tgbotjs:
    platform: linux/amd64
    image: tgbot
    build:
      context: happyhacking-telegraf
      dockerfile: Dockerfile
